"""test running migrations

Revision ID: 1d963b433019
Revises: e148491bdcdf
Create Date: 2024-01-28 12:38:03.408533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d963b433019'
down_revision = 'e148491bdcdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
