"""test running migrations

Revision ID: a44cd0299962
Revises: 9d5da7cb7b2b
Create Date: 2024-01-28 12:36:54.379859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44cd0299962'
down_revision = '9d5da7cb7b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
